name: Android CI

# Triggers the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository's code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 11 (Android requires JDK 8 or above)
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      # Download and cache Gradle dependencies
      - name: Download dependencies
        run: ./gradlew build --stacktrace

      # Build the APK
      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace

      # Upload the built APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
