name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '21'

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 34
        build-tools: 34.0.0

    - name: Append sdk.dir to local.properties
      run: |
        sed -i '/^sdk.dir=/d' local.properties  # Remove any existing sdk.dir line
        echo "" >> local.properties  # Add a new line before appending sdk.dir
        echo "sdk.dir=$ANDROID_HOME" >> local.properties
        cat local.properties  # Output the file contents for debugging
    
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      
    - name: Decode keystore
      run: echo "${{ secrets.KEYSTORE_BASE64}}" | base64 --decode > /release-key.jks
    
    - name: List files
      run: ls -al
  
    - name: Build with Gradle
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }} # Add your keystore password secret
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}               # Add your key alias secret
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}         # Add your key password secret
          
      run: ./gradlew build --stacktrace

      
    # Upload the built APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
